// src/pages/Index/components/DishGrid/index.tsx
import { Grid } from "@mui/material";
import React from "react";

import DishItem from "./components/DishItem";

import type { Dish } from "~/api/models";

export type DishGridProps = {
  dishes: Dish[];
};

export default function DishGrid({
  dishes,
}: DishGridProps): JSX.Element | null {
  return (
    <Grid container>
      {dishes.map((dish) => (
        <DishItem key={dish.id} dish={dish} />
      ))}
    </Grid>
  );
}

// web/src/lib/components/DishGrid/index.svelte
<script lang="ts">
  import type { Dish } from "$lib/api/db/models";
  import DishItem from "./components/DishItem.svelte";

  export let dishes: Dish[];
</script>

<div class="container">
  {#each dishes as dish}
    <DishItem {dish} />
  {/each}
</div>

<style>
  .container {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(160px, 1fr));
    grid-gap: 1.2rem;
  }
</style>
